export const background = "#ffffff";
export const backgroundErrorLogin = "rgba(255, 6, 8, 0.6)";
export const borderErrorLogin = "#ff0600";
export const buttonPrimary = "#ff4081";
export const iconWhite = "#ffffff";
export const lineForecast = "#a8e1d4";
export const lineReading = "#3E50B4";
export const loginTextBackground = "rgba(0, 0, 0, 0.2)";
export const titleLightBackground = "#eeeeee";
// FIXME: https://github.com/facebook/react-native/issues/3652
export const loginTextBorder = "#979fd1";
// export const loginTextBorder = "rgba(255, 255, 255, 0.5)";
export const primaryBlue = "#3E50B4";
export const powerNumber = "#ff4081";
export const secondaryBlue = "#536DFE";
export const transparent = "transparent";
export const white = "#ffffff";
export const black = "#000000";
export const lightGrey = "#cccccc";
export const grey = "#999999";
export const aquaGreen = "#12b0c5";
export const acidGreen = "#cddc39";
export const backgroundBlackOpacity = "rgba(0, 0, 0, 0.2)";
//
export const demographicsSection = "#536DFE";
export const buildingsSection = "#3E50B4";
export const heatingSection = "#ff4081";
export const coolingSection = "#12b0c5";
export const statisticsSection = "#cddc39";
