# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iwapp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iwapp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'iwappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
